@baseUrl = http://localhost:1414/products

### Get all products
GET {{baseUrl}}

### Get a product by id
GET {{baseUrl}}/1

### Create a new product 
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Product 4",
  "price": 400,
  "quantity": 4
}

### Update all field a product
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name": "Product 1-2",
  "price": 101,
  "quantity": 11
}

### Delete product by id
DELETE {{baseUrl}}/1